apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx-gitops
  name: my-nginx-gitops-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx-gitops

